services:
  - type: web
    name: meshalstock
    env: python
    region: frankfurt
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.5
